"""
Django settings for spartamarket_DRF project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path # 경로 모듈    
import os # 운영체제 모듈

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # 프로젝트 디렉토리


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nodst1$l5&=_g846n4(lizu6_3^9j8q8kckd-o1175tu-*so8='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # 장고 관리자
    'django.contrib.auth', # 장고 인증
    'django.contrib.contenttypes', # 장고 콘텐츠 타입
    'django.contrib.sessions', # 장고 세션
    'django.contrib.messages', # 장고 메시지
    'django.contrib.staticfiles', # 장고 정적 파일
    'rest_framework', # 장고 레스트 프레임워크
    'rest_framework.authtoken', # 장고 레스트 프레임워크 인증 토큰
    'accounts', # 계정 앱
    'products', # 상품 앱
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # 장고 보안 미들웨어
    'django.contrib.sessions.middleware.SessionMiddleware', # 장고 세션 미들웨어
    'django.middleware.common.CommonMiddleware', # 장고 공통 미들웨어
    'django.middleware.csrf.CsrfViewMiddleware', # 장고 CSRF 미들웨어
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 장고 인증 미들웨어
    'django.contrib.messages.middleware.MessageMiddleware', # 장고 메시지 미들웨어
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # 장고 클릭 잡기 미들웨어
]

ROOT_URLCONF = 'spartamarket_DRF.urls' # 루트 URL 설정

TEMPLATES = [ # 템플릿 설정
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # 장고 템플릿 백엔드
        'DIRS': [], # 템플릿 디렉토리
        'APP_DIRS': True, # 앱 디렉토리
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spartamarket_DRF.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = { # 데이터베이스 설정
    'default': { # 기본 데이터베이스
        'ENGINE': 'django.db.backends.sqlite3', # 데이터베이스 엔진
        'NAME': BASE_DIR / 'db.sqlite3', # 데이터베이스 이름
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr' # 언어 코드

TIME_ZONE = 'Asia/Seoul' # 시간대

USE_I18N = True # 국제화 사용

USE_TZ = True # 시간대 사용


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/' # 정적 파일 URL

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # 기본 자동 키 필드 타입

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = { # 레스트 프레임워크 설정
    'DEFAULT_AUTHENTICATION_CLASSES': [ # 기본 인증 클래스
        'rest_framework.authentication.TokenAuthentication', # 토큰 인증 클래스
    ],
}

MEDIA_URL = '/media/' # 미디어 URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # 미디어 루트